# Generated by Django 4.2 on 2023-06-24 15:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("warehouse", "0002_rack_shelf_warehouse_zone_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="productstoragelink",
            old_name="product_id",
            new_name="product",
        ),
        migrations.RenameField(
            model_name="productstoragelink",
            old_name="shelf_id",
            new_name="shelf",
        ),
    ]
